name: 04_ageing_environ

dependencies:
- python == 3.7
- numpy == 1.15
- pandas == 0.23.3
- matplotlib == 2.2.3
- ipykernel == 5.1.0
- seaborn == 0.9.0
- pip
- pip:
  - git+https://github.com/A-Fisk/actiPy.git@master
  - git+https://github.com/A-Fisk/sleepPy.git@master

